-- AlterTable
ALTER TABLE "Report" ADD COLUMN     "rating" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "lat" SET DATA TYPE TEXT,
ALTER COLUMN "lon" DROP NOT NULL,
ALTER COLUMN "lon" SET DATA TYPE TEXT;
